# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField(default=0)),
                ('emi_amount', models.IntegerField(default=0)),
                ('no_of_emis', models.IntegerField(default=0)),
                ('rate_of_intrest', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='bills',
            name='appid',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='emi_amount',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='intrest_amount',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='no_of_emis',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='rate_of_intrest',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='share_amount',
        ),
        migrations.RemoveField(
            model_name='savingaccount',
            name='share_amount',
        ),
        migrations.AddField(
            model_name='bills',
            name='created_at',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='bills',
            name='emi_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bills',
            name='interest_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bills',
            name='loanid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bills',
            name='paid_emi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bills',
            name='rm_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='organisationaccount',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='organisationaccount',
            name='bill_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='savingaccount',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='savingaccount',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='loan',
            name='appid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apploan', to='people.Application'),
        ),
    ]
