# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_specialloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialloan',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
