# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_specialloan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialloan',
            name='created_at',
            field=models.DateField(default=None),
        ),
    ]
