# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_specialloan_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialloan',
            old_name='special_loan_amout',
            new_name='special_loan_amount',
        ),
    ]
